In [1]:
import os
os.environ.pop('MPLBACKEND', None)

'module://matplotlib_inline.backend_inline'

In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
irr_data = pd.read_csv ("../dataset/train.csv")

In [4]:
irr_data

,id,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,...,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,...,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East,Low
1,1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,...,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South,Low
2,2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,...,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North,Low
3,3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,...,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South,Medium
4,4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,...,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629995,629995,Clay,6.54,13.45,1.15,1.86,26.65,26.86,1041.33,10.62,...,Rice,Sowing,Kharif,Sprinkler,River,4.35,No,118.36,South,Medium
629996,629996,Clay,7.03,54.49,0.96,2.35,36.99,88.00,1419.57,9.93,...,Sugarcane,Vegetative,Kharif,Drip,Groundwater,12.97,Yes,40.75,Central,Medium
629997,629997,Clay,6.52,11.98,0.93,0.38,37.82,70.98,88.45,8.19,...,Potato,Vegetative,Zaid,Canal,Reservoir,13.58,Yes,2.62,South,High
629998,629998,Clay,5.93,42.86,0.33,3.39,34.99,94.58,2433.92,9.88,...,Sugarcane,Vegetative,Zaid,Sprinkler,Groundwater,0.79,Yes,90.00,East,Low
629999,629999,Loamy,7.02,35.36,1.19,0.46,26.92,64.33,1269.55,7.91,...,Maize,Harvest,Kharif,Drip,Reservoir,3.80,No,112.93,West,Low

In [5]:
irr_data.describe()

,id,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,Previous_Irrigation_mm
count,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000
mean,314999.500000,6.482497,37.304482,0.922858,1.744605,26.998166,61.563180,1462.207566,7.513382,10.375394,7.517745,62.318177
std,181865.479132,0.922504,16.377082,0.365808,0.952321,8.623621,19.708152,612.989738,1.999322,5.689458,4.218124,34.246939
min,0.000000,4.800000,8.000000,0.300000,0.100000,12.000000,25.000000,0.380000,4.000000,0.500000,0.300000,0.020000
25%,157499.750000,5.690000,23.340000,0.610000,0.930000,19.517500,45.390000,954.570000,5.760000,5.280000,3.880000,33.140000
50%,314999.500000,6.440000,37.750000,0.910000,1.740000,26.960000,61.650000,1467.160000,7.580000,10.480000,7.380000,61.150000
75%,472499.250000,7.270000,51.270000,1.220000,2.580000,34.540000,79.120000,2054.280000,9.250000,15.430000,11.140000,92.690000
max,629999.000000,8.200000,64.990000,1.600000,3.500000,42.000000,94.990000,2499.690000,11.000000,20.000000,15.000000,119.990000

In [6]:
class_mapping = {"Low": 0, "Medium": 1, "High": 2}
irr_data ["class_enc"] = irr_data["Irrigation_Need"].map(class_mapping)

In [8]:
corr = irr_data.select_dtypes(include="number").corr()
sns.heatmap(corr, cmap="YlGnBu")
plt.show()

2026-04-30 22:44:41.517 python[30908:13740485] +[IMKClient subclass]: chose IMKClient_Modern
2026-04-30 22:44:41.517 python[30908:13740485] +[IMKInputSession subclass]: chose IMKInputSession_Modern

In [11]:
from sklearn.model_selection import StratifiedShuffleSplit
splitobj = StratifiedShuffleSplit (n_splits=1, test_size= 0.2)
for trainidx, testidx in splitobj.split(irr_data, irr_data["class_enc"]):
    strat_train_set = irr_data.loc[trainidx]
    strat_val_set = irr_data.loc[testidx]

In [ ]:
strat_train_set.to_pickle("strat_train_set")
strat_val_set.to_pickle("strat_val_set")

:

In [15]:
strat_train_set.info()

<class 'pandas.core.frame.DataFrame'>
Index: 504000 entries, 434935 to 619674
Data columns (total 22 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       504000 non-null  int64
 1   Soil_Type                504000 non-null  object
 2   Soil_pH                  504000 non-null  float64
 3   Soil_Moisture            504000 non-null  float64
 4   Organic_Carbon           504000 non-null  float64
 5   Electrical_Conductivity  504000 non-null  float64
 6   Temperature_C            504000 non-null  float64
 7   Humidity                 504000 non-null  float64
 8   Rainfall_mm              504000 non-null  float64
 9   Sunlight_Hours           504000 non-null  float64
 10  Wind_Speed_kmh           504000 non-null  float64
 11  Crop_Type                504000 non-null  object
 12  Crop_Growth_Stage        504000 non-null  object
 13  Season                   504000 non-null  object
 14  Irrigation_Type          504000 non-null  object
 15  Water_Source             504000 non-null  object
 16  Field_Area_hectare       504000 non-null  float64
 17  Mulching_Used            504000 non-null  object
 18  Previous_Irrigation_mm   504000 non-null  float64
 19  Region                   504000 non-null  object
 20  Irrigation_Need          504000 non-null  object
 21  class_enc                504000 non-null  int64
dtypes: float64(11), int64(2), object(9)
memory usage: 88.4+ MB

In [28]:
cats = strat_train_set.select_dtypes(include='object')
cats_unique = cats.drop_duplicates()
num_cats = cats.nunique()
num_cats

Soil_Type            4
Crop_Type            6
Crop_Growth_Stage    4
Season               3
Irrigation_Type      4
Water_Source         4
Mulching_Used        2
Region               5
Irrigation_Need      3
dtype: int64